# Generated by Django 2.1.2 on 2018-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.CharField(default='https://i.imgur.com/IcvbvO5.jpg', max_length=150),
        ),
    ]
