# Generated by Django 2.1.2 on 2018-10-15 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='contest',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main_app.Post'),
            preserve_default=False,
        ),
    ]
