# Generated by Django 2.1.2 on 2018-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.CharField(default='https://via.placeholder.com/350x350', max_length=150),
        ),
    ]
