# Generated by Django 2.1.2 on 2018-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
